// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PhoneType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace My.Models {

  /// <summary>Holder for reflection information generated from PhoneType.proto</summary>
  public static partial class PhoneTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for PhoneType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PhoneTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9QaG9uZVR5cGUucHJvdG8SCU15Lk1vZGVscyorCglQaG9uZVR5cGUSCgoG",
            "TU9CSUxFEAASCAoESE9NRRABEggKBFdPUksQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::My.Models.PhoneType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PhoneType {
    [pbr::OriginalName("MOBILE")] Mobile = 0,
    [pbr::OriginalName("HOME")] Home = 1,
    [pbr::OriginalName("WORK")] Work = 2,
  }

  #endregion

}

#endregion Designer generated code
